export var players = {
 player1: {
   score: 0,
   marks: 900,
   name: 'Han Solo',
   internalName: 'proxyplayer1',
   seat: 1,
   pass: false,
   bet: [],
   fold: false,
   answer: 'äpple',
   rightAnswerNr: 0,
   seated: false,
   ready: false,
 },
 player2: {
  score: 0,
  marks: 1000,
  name: 'Rey',
  seat: 2,
  pass: false,
  bet: [],
  fold: false,
  answer: 'äpple',
  rightAnswerNr: 2,
  seated: false,
  ready: false,
 },
 player3: {
  score: 0,
  marks: 1000,
  name: 'R2D2',
  seat: 3,
  pass: false,
  bet: [],
  fold: false,
  answer: 'äpple',
  rightAnswerNr: 0,
  seated: false,
  ready: false,
 },
 player4: {
  score: 0,
  marks: 1000,
  name: 'Leia',
  seat: 4,
  pass: false,
  bet: [],
  fold: false,
  answer: 'äpple',
  rightAnswerNr: 0,
  seated: false,
  ready: false,
 },
 player5: {
  score: 0,
  marks: 1000,
  name: 'Luke',
  seat: 5,
  pass: false,
  bet: [],
  fold: false,
  answer: 'päron',
  rightAnswerNr: 0,
  seated: false,
  ready: false,
 },

};
  